package io.github.sonicalgo.dhan.usecase

import com.fasterxml.jackson.annotation.JsonProperty
import io.github.sonicalgo.builder.GenerateBuilder
import io.github.sonicalgo.dhan.common.*
import io.github.sonicalgo.dhan.config.ApiClient
import io.github.sonicalgo.dhan.config.DhanConfig

/**
 * Modifies an existing pending order via API.
 */
@JvmSynthetic
internal fun executeModifyOrder(apiClient: ApiClient, config: DhanConfig, orderId: String, params: ModifyOrderParams): OrderAction {
    val request = params.copy(dhanClientId = params.dhanClientId ?: config.clientId)
    return apiClient.put(
        endpoint = "/orders/$orderId",
        body = request
    )
}

/**
 * Request parameters for modifying an existing order.
 *
 * Only orders in PENDING or PART_TRADED status can be modified.
 *
 * @property dhanClientId User identification. Auto-injected from config if not provided.
 * @property orderId Order specific identification generated by Dhan.
 * @property orderType Order type: LIMIT, MARKET, STOP_LOSS, STOP_LOSS_MARKET.
 * @property legName Leg name for BO/CO orders: ENTRY_LEG, TARGET_LEG, STOP_LOSS_LEG.
 * @property quantity Quantity to be modified.
 * @property price Price to be modified.
 * @property disclosedQuantity Number of shares visible (must be greater than 30% of quantity).
 * @property triggerPrice Price at which order is triggered. Required for stop-loss orders.
 * @property validity Order validity: DAY or IOC.
 * @see <a href="https://dhanhq.co/docs/v2/orders/">DhanHQ Orders API</a>
 */
@GenerateBuilder
data class ModifyOrderParams(
    @JsonProperty("dhanClientId")
    val dhanClientId: String? = null,

    @JsonProperty("orderId")
    val orderId: String,

    @JsonProperty("orderType")
    val orderType: OrderType,

    @JsonProperty("legName")
    val legName: LegName? = null,

    @JsonProperty("quantity")
    val quantity: Int? = null,

    @JsonProperty("price")
    val price: Double? = null,

    @JsonProperty("disclosedQuantity")
    val disclosedQuantity: Int? = null,

    @JsonProperty("triggerPrice")
    val triggerPrice: Double? = null,

    @JsonProperty("validity")
    val validity: Validity
)
