package io.github.sonicalgo.dhan.common

import com.fasterxml.jackson.annotation.JsonProperty

// ==================== Order Responses ====================

/**
 * Response from place/modify/cancel order operations.
 *
 * @property orderId Order specific identification generated by Dhan.
 * @property orderStatus Status of the order: TRANSIT, PENDING, REJECTED, CANCELLED, TRADED, EXPIRED.
 * @see <a href="https://dhanhq.co/docs/v2/orders/">DhanHQ Orders API</a>
 */
data class OrderAction(
    @JsonProperty("orderId")
    val orderId: String,

    @JsonProperty("orderStatus")
    val orderStatus: OrderStatus
)

/**
 * Order details from order book.
 *
 * @property dhanClientId User identification.
 * @property orderId Order specific identification generated by Dhan.
 * @property correlationId User/partner generated ID for tracking back.
 * @property orderStatus Status of the order: TRANSIT, PENDING, REJECTED, CANCELLED, PART_TRADED, TRADED, EXPIRED.
 * @property transactionType Transaction type: BUY or SELL.
 * @property exchangeSegment Exchange segment of the instrument.
 * @property productType Product type: CNC, INTRADAY, MARGIN, MTF, CO, BO.
 * @property orderType Order type: LIMIT, MARKET, STOP_LOSS, STOP_LOSS_MARKET.
 * @property validity Order validity: DAY or IOC.
 * @property tradingSymbol Trading symbol of the instrument.
 * @property securityId Exchange standard ID for each scrip.
 * @property quantity Number of shares for the order.
 * @property disclosedQuantity Number of shares visible.
 * @property price Price at which order is placed.
 * @property triggerPrice Price at which order is triggered.
 * @property afterMarketOrder Flag for orders placed after market hours.
 * @property boProfitValue Bracket Order target price change.
 * @property boStopLossValue Bracket Order stop-loss price change.
 * @property legName Leg name for BO/CO orders: ENTRY_LEG, TARGET_LEG, STOP_LOSS_LEG.
 * @property createTime Order creation time in YYYY-MM-DD HH:MM:SS format.
 * @property updateTime Order update time in YYYY-MM-DD HH:MM:SS format.
 * @property exchangeTime Exchange acknowledgment time in YYYY-MM-DD HH:MM:SS format.
 * @property drvExpiryDate Derivative expiry date.
 * @property drvOptionType Derivative option type: CALL or PUT.
 * @property drvStrikePrice Derivative strike price.
 * @property omsErrorCode OMS error code if order rejected.
 * @property omsErrorDescription OMS error description if order rejected.
 * @property algoId Algo ID if order placed via algo.
 * @property remainingQuantity Remaining quantity to be executed (quantity - filledQty).
 * @property averageTradedPrice Average traded price.
 * @property filledQty Filled quantity.
 * @see <a href="https://dhanhq.co/docs/v2/orders/">DhanHQ Orders API</a>
 */
data class OrderBookItem(
    @JsonProperty("dhanClientId")
    val dhanClientId: String,

    @JsonProperty("orderId")
    val orderId: String,

    @JsonProperty("correlationId")
    val correlationId: String? = null,

    @JsonProperty("orderStatus")
    val orderStatus: OrderStatus,

    @JsonProperty("transactionType")
    val transactionType: TransactionType,

    @JsonProperty("exchangeSegment")
    val exchangeSegment: ExchangeSegment,

    @JsonProperty("productType")
    val productType: ProductType,

    @JsonProperty("orderType")
    val orderType: OrderType,

    @JsonProperty("validity")
    val validity: Validity,

    @JsonProperty("tradingSymbol")
    val tradingSymbol: String,

    @JsonProperty("securityId")
    val securityId: String,

    @JsonProperty("quantity")
    val quantity: Int,

    @JsonProperty("disclosedQuantity")
    val disclosedQuantity: Int? = null,

    @JsonProperty("price")
    val price: Double,

    @JsonProperty("triggerPrice")
    val triggerPrice: Double? = null,

    @JsonProperty("afterMarketOrder")
    val afterMarketOrder: Boolean? = null,

    @JsonProperty("boProfitValue")
    val boProfitValue: Double? = null,

    @JsonProperty("boStopLossValue")
    val boStopLossValue: Double? = null,

    @JsonProperty("legName")
    val legName: LegName? = null,

    @JsonProperty("createTime")
    val createTime: String? = null,

    @JsonProperty("updateTime")
    val updateTime: String? = null,

    @JsonProperty("exchangeTime")
    val exchangeTime: String? = null,

    @JsonProperty("drvExpiryDate")
    val drvExpiryDate: String? = null,

    @JsonProperty("drvOptionType")
    val drvOptionType: DrvOptionType? = null,

    @JsonProperty("drvStrikePrice")
    val drvStrikePrice: Double? = null,

    @JsonProperty("omsErrorCode")
    val omsErrorCode: String? = null,

    @JsonProperty("omsErrorDescription")
    val omsErrorDescription: String? = null,

    @JsonProperty("algoId")
    val algoId: String? = null,

    @JsonProperty("remainingQuantity")
    val remainingQuantity: Int? = null,

    @JsonProperty("averageTradedPrice")
    val averageTradedPrice: Double? = null,

    @JsonProperty("filledQty")
    val filledQty: Int? = null
)

/**
 * Trade details from trade book.
 *
 * @property dhanClientId User identification.
 * @property orderId Order specific identification generated by Dhan.
 * @property exchangeOrderId Exchange order ID.
 * @property exchangeTradeId Exchange trade ID.
 * @property transactionType Transaction type: BUY or SELL.
 * @property exchangeSegment Exchange segment of the instrument.
 * @property productType Product type: CNC, INTRADAY, MARGIN, MTF, CO, BO.
 * @property orderType Order type: LIMIT, MARKET, STOP_LOSS, STOP_LOSS_MARKET.
 * @property tradingSymbol Trading symbol of the instrument.
 * @property securityId Exchange standard ID for each scrip.
 * @property tradedQuantity Traded quantity.
 * @property tradedPrice Traded price.
 * @property createTime Trade creation time in YYYY-MM-DD HH:MM:SS format.
 * @property updateTime Trade update time in YYYY-MM-DD HH:MM:SS format.
 * @property exchangeTime Exchange acknowledgment time in YYYY-MM-DD HH:MM:SS format.
 * @property drvExpiryDate Derivative expiry date.
 * @property drvOptionType Derivative option type: CALL or PUT.
 * @property drvStrikePrice Derivative strike price.
 * @see <a href="https://dhanhq.co/docs/v2/orders/">DhanHQ Orders API</a>
 */
data class TradeBookItem(
    @JsonProperty("dhanClientId")
    val dhanClientId: String,

    @JsonProperty("orderId")
    val orderId: String,

    @JsonProperty("exchangeOrderId")
    val exchangeOrderId: String? = null,

    @JsonProperty("exchangeTradeId")
    val exchangeTradeId: String? = null,

    @JsonProperty("transactionType")
    val transactionType: TransactionType,

    @JsonProperty("exchangeSegment")
    val exchangeSegment: ExchangeSegment,

    @JsonProperty("productType")
    val productType: ProductType,

    @JsonProperty("orderType")
    val orderType: OrderType? = null,

    @JsonProperty("tradingSymbol")
    val tradingSymbol: String? = null,

    @JsonProperty("securityId")
    val securityId: String,

    @JsonProperty("tradedQuantity")
    val tradedQuantity: Int,

    @JsonProperty("tradedPrice")
    val tradedPrice: Double,

    @JsonProperty("createTime")
    val createTime: String? = null,

    @JsonProperty("updateTime")
    val updateTime: String? = null,

    @JsonProperty("exchangeTime")
    val exchangeTime: String? = null,

    @JsonProperty("drvExpiryDate")
    val drvExpiryDate: String? = null,

    @JsonProperty("drvOptionType")
    val drvOptionType: DrvOptionType? = null,

    @JsonProperty("drvStrikePrice")
    val drvStrikePrice: Double? = null
)

// ==================== Market Quote Responses ====================

/**
 * OHLC price data.
 *
 * @property open Day opening price.
 * @property close Day closing price.
 * @property high Day high price.
 * @property low Day low price.
 */
data class OhlcData(
    @JsonProperty("open")
    val open: Double,

    @JsonProperty("close")
    val close: Double,

    @JsonProperty("high")
    val high: Double,

    @JsonProperty("low")
    val low: Double
)

/**
 * Market depth level data for REST API responses.
 *
 * Note: This class is used for REST API market quote responses.
 * For WebSocket market feed depth data, see [io.github.sonicalgo.dhan.websocket.marketFeed.DepthLevel]
 * which uses String for price (formatted to 2 decimal places).
 *
 * @property quantity Quantity at this depth level.
 * @property orders Number of orders at this level.
 * @property price Price at this depth level (as Double from REST API).
 */
data class DepthLevel(
    @JsonProperty("quantity")
    val quantity: Int,

    @JsonProperty("orders")
    val orders: Int,

    @JsonProperty("price")
    val price: Double
)

/**
 * Market depth data.
 *
 * @property buy List of buy depth levels.
 * @property sell List of sell depth levels.
 */
data class MarketDepth(
    @JsonProperty("buy")
    val buy: List<DepthLevel>,

    @JsonProperty("sell")
    val sell: List<DepthLevel>
)

/**
 * LTP quote data.
 *
 * @property lastPrice Last traded price of the instrument.
 */
data class Ltp(
    @JsonProperty("last_price")
    val lastPrice: Double
)

/**
 * OHLC quote data with LTP.
 *
 * @property lastPrice Last traded price.
 * @property ohlc OHLC (Open, High, Low, Close) data.
 */
data class OhlcQuote(
    @JsonProperty("last_price")
    val lastPrice: Double,

    @JsonProperty("ohlc")
    val ohlc: OhlcData
)

/**
 * Full market quote with depth.
 *
 * @property averagePrice Volume-weighted daily average price.
 * @property buyQuantity Total pending buy order quantity.
 * @property sellQuantity Total pending sell order quantity.
 * @property depth Market depth with buy and sell levels.
 * @property lastPrice Most recent traded price.
 * @property lastQuantity Most recent trade quantity.
 * @property lastTradeTime Timestamp of last trade.
 * @property lowerCircuitLimit Current lower circuit level.
 * @property upperCircuitLimit Current upper circuit level.
 * @property netChange Change from previous close.
 * @property ohlc OHLC (Open, High, Low, Close) data.
 * @property openInterest Open Interest (for derivatives).
 * @property oiDayHigh Highest daily Open Interest.
 * @property oiDayLow Lowest daily Open Interest.
 * @property volume Total daily traded volume.
 */
data class FullQuote(
    @JsonProperty("average_price")
    val averagePrice: Double? = null,

    @JsonProperty("buy_quantity")
    val buyQuantity: Int? = null,

    @JsonProperty("sell_quantity")
    val sellQuantity: Int? = null,

    @JsonProperty("depth")
    val depth: MarketDepth? = null,

    @JsonProperty("last_price")
    val lastPrice: Double,

    @JsonProperty("last_quantity")
    val lastQuantity: Int? = null,

    @JsonProperty("last_trade_time")
    val lastTradeTime: String? = null,

    @JsonProperty("lower_circuit_limit")
    val lowerCircuitLimit: Double? = null,

    @JsonProperty("upper_circuit_limit")
    val upperCircuitLimit: Double? = null,

    @JsonProperty("net_change")
    val netChange: Double? = null,

    @JsonProperty("ohlc")
    val ohlc: OhlcData? = null,

    @JsonProperty("oi")
    val openInterest: Int? = null,

    @JsonProperty("oi_day_high")
    val oiDayHigh: Int? = null,

    @JsonProperty("oi_day_low")
    val oiDayLow: Int? = null,

    @JsonProperty("volume")
    val volume: Int? = null
)

// ==================== Historical Data Responses ====================

/**
 * Historical OHLCV data.
 */
data class HistoricalData(
    @JsonProperty("open")
    val open: List<Double>,

    @JsonProperty("high")
    val high: List<Double>,

    @JsonProperty("low")
    val low: List<Double>,

    @JsonProperty("close")
    val close: List<Double>,

    @JsonProperty("volume")
    val volume: List<Long>,

    @JsonProperty("start_Time")
    val timestamp: List<Long>
)

// ==================== Internal Response Wrappers ====================

/**
 * Internal wrapper for market quote responses.
 */
internal data class MarketQuoteResponse<T>(
    @JsonProperty("data")
    val data: Map<String, Map<String, T>>? = null,

    @JsonProperty("status")
    val status: String? = null
)
