package io.github.sonicalgo.dhan.model.response

import com.fasterxml.jackson.annotation.JsonProperty
import io.github.sonicalgo.dhan.model.enums.DataPlanStatus
import io.github.sonicalgo.dhan.model.enums.DdpiStatus
import io.github.sonicalgo.dhan.model.enums.MtfStatus

/**
 * User profile information.
 *
 * Response from GET /profile endpoint.
 *
 * @property dhanClientId User specific identification generated by Dhan
 * @property tokenValidity Token expiry date/time
 * @property activeSegment Trading segments available
 * @property ddpi DDPI status: Active or Deactive
 * @property mtf MTF status: Active or Deactive
 * @property dataPlan Data API subscription status: Active or Deactive
 * @property dataValidity Data subscription expiry
 *
 * @see <a href="https://dhanhq.co/docs/v2/authentication/">DhanHQ Authentication</a>
 */
data class UserProfile(
    @JsonProperty("dhanClientId")
    val dhanClientId: String,

    @JsonProperty("tokenValidity")
    val tokenValidity: String? = null,

    @JsonProperty("activeSegment")
    val activeSegment: String? = null,

    @JsonProperty("ddpi")
    val ddpi: DdpiStatus? = null,

    @JsonProperty("mtf")
    val mtf: MtfStatus? = null,

    @JsonProperty("dataPlan")
    val dataPlan: DataPlanStatus? = null,

    @JsonProperty("dataValidity")
    val dataValidity: String? = null
)

/**
 * Response from set IP operation.
 *
 * Response from POST /ip/setIP and PUT /ip/modifyIP endpoints.
 *
 * @property message Confirmation message
 * @property status SUCCESS or error status
 *
 * @see <a href="https://dhanhq.co/docs/v2/authentication/">DhanHQ Authentication</a>
 */
data class SetIpResult(
    @JsonProperty("message")
    val message: String,

    @JsonProperty("status")
    val status: String
)

/**
 * Static IP configuration details.
 *
 * Response from GET /ip/getIP endpoint.
 *
 * @property primaryIp Current primary static IP
 * @property modifyDatePrimary Next modification date for primary IP (YYYY-MM-DD)
 * @property secondaryIp Current secondary static IP
 * @property modifyDateSecondary Next modification date for secondary IP (YYYY-MM-DD)
 *
 * @see <a href="https://dhanhq.co/docs/v2/authentication/">DhanHQ Authentication</a>
 */
data class IpConfiguration(
    @JsonProperty("primaryIP")
    val primaryIp: String? = null,

    @JsonProperty("modifyDatePrimary")
    val modifyDatePrimary: String? = null,

    @JsonProperty("secondaryIP")
    val secondaryIp: String? = null,

    @JsonProperty("modifyDateSecondary")
    val modifyDateSecondary: String? = null
)
