package io.github.sonicalgo.dhan.model.response

import com.fasterxml.jackson.annotation.JsonProperty
import io.github.sonicalgo.dhan.model.enums.EdisStatus

/**
 * Response from EDIS form generation.
 *
 * @property dhanClientId User specific identification generated by Dhan
 * @property edisFormHtml Escaped HTML Form requiring user rendering
 *
 * @see <a href="https://dhanhq.co/docs/v2/edis/">DhanHQ EDIS API</a>
 */
data class EdisForm(
    @JsonProperty("dhanClientId")
    val dhanClientId: String,

    @JsonProperty("edisFormHtml")
    val edisFormHtml: String
)

/**
 * Response from EDIS status inquiry.
 *
 * @property clientId User specific identification
 * @property isin International Securities Identification Number
 * @property totalQuantity Total number of shares for given stock
 * @property approvedQuantity Number of approved stocks
 * @property status Status of the edis order
 * @property remarks Remarks of the order status
 *
 * @see <a href="https://dhanhq.co/docs/v2/edis/">DhanHQ EDIS API</a>
 */
data class EdisStatus(
    @JsonProperty("clientId")
    val clientId: String,

    @JsonProperty("isin")
    val isin: String,

    @JsonProperty("totalQty")
    val totalQuantity: Int,

    @JsonProperty("aprvdQty")
    val approvedQuantity: Int,

    @JsonProperty("status")
    val status: EdisStatus,

    @JsonProperty("remarks")
    val remarks: String? = null
)
