package io.github.sonicalgo.dhan.model.response

import com.fasterxml.jackson.annotation.JsonProperty
import io.github.sonicalgo.dhan.model.enums.*

/**
 * Forever order details from order book.
 *
 * Response from GET /forever/all endpoint.
 *
 * @property dhanClientId User specific identification generated by Dhan
 * @property orderId Order specific identification generated by Dhan
 * @property orderStatus Current status
 * @property transactionType BUY or SELL
 * @property exchangeSegment Exchange segment
 * @property productType CNC, INTRADAY, MARGIN, CO, BO
 * @property orderType SINGLE or OCO
 * @property tradingSymbol Instrument symbol
 * @property securityId Exchange standard ID
 * @property quantity Order quantity
 * @property price Order price
 * @property triggerPrice Trigger price
 * @property legName TARGET_LEG or STOP_LOSS_LEG
 * @property createTime Creation timestamp
 * @property updateTime Last update timestamp
 * @property exchangeTime Exchange receipt time
 * @property drvExpiryDate Derivative expiry date
 * @property drvOptionType CALL or PUT
 * @property drvStrikePrice Option strike price
 *
 * @see <a href="https://dhanhq.co/docs/v2/forever/">DhanHQ Forever Order API</a>
 */
data class ForeverOrderBookItem(
    @JsonProperty("dhanClientId")
    val dhanClientId: String,

    @JsonProperty("orderId")
    val orderId: String,

    @JsonProperty("orderStatus")
    val orderStatus: OrderStatus,

    @JsonProperty("transactionType")
    val transactionType: TransactionType,

    @JsonProperty("exchangeSegment")
    val exchangeSegment: ExchangeSegment,

    @JsonProperty("productType")
    val productType: ProductType,

    @JsonProperty("orderType")
    val orderType: String? = null,

    @JsonProperty("tradingSymbol")
    val tradingSymbol: String? = null,

    @JsonProperty("securityId")
    val securityId: String,

    @JsonProperty("quantity")
    val quantity: Int,

    @JsonProperty("price")
    val price: Double,

    @JsonProperty("triggerPrice")
    val triggerPrice: Double,

    @JsonProperty("legName")
    val legName: LegName? = null,

    @JsonProperty("createTime")
    val createTime: String? = null,

    @JsonProperty("updateTime")
    val updateTime: String? = null,

    @JsonProperty("exchangeTime")
    val exchangeTime: String? = null,

    @JsonProperty("drvExpiryDate")
    val drvExpiryDate: String? = null,

    @JsonProperty("drvOptionType")
    val drvOptionType: DrvOptionType? = null,

    @JsonProperty("drvStrikePrice")
    val drvStrikePrice: Double? = null
)
