package io.github.sonicalgo.dhan.model.response

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Fund limit and margin details.
 *
 * Contains available balance, margin, and fund utilization details.
 *
 * @property dhanClientId User specific identification generated by Dhan
 * @property availableBalance Available funds for trading
 * @property sodLimit Start-of-day balance
 * @property collateralAmount Funds received as collateral
 * @property receivableAmount Settlement receivables
 * @property utilizedAmount Daily utilized amount
 * @property blockedPayoutAmount Funds blocked for payout
 * @property withdrawableBalance Amount eligible for bank withdrawal
 *
 * @see <a href="https://dhanhq.co/docs/v2/funds/">DhanHQ Funds API</a>
 */
data class FundLimit(
    @JsonProperty("dhanClientId")
    val dhanClientId: String,

    @JsonProperty("availabelBalance")  // Note: API has typo "availabelBalance"
    val availableBalance: Double,

    @JsonProperty("sodLimit")
    val sodLimit: Double,

    @JsonProperty("collateralAmount")
    val collateralAmount: Double,

    @JsonProperty("receiveableAmount")
    val receivableAmount: Double,

    @JsonProperty("utilizedAmount")
    val utilizedAmount: Double,

    @JsonProperty("blockedPayoutAmount")
    val blockedPayoutAmount: Double,

    @JsonProperty("withdrawableBalance")
    val withdrawableBalance: Double
)

/**
 * Margin calculation result.
 *
 * Contains margin requirements for an order.
 *
 * @property totalMargin Total required margin
 * @property spanMargin SPAN margin component
 * @property exposureMargin Exposure margin component
 * @property availableBalance Account available funds
 * @property variableMargin VAR margin requirement
 * @property insufficientBalance Shortfall amount (if any)
 * @property brokerage Brokerage charges
 * @property leverage Margin leverage ratio
 *
 * @see <a href="https://dhanhq.co/docs/v2/funds/">DhanHQ Funds API</a>
 */
data class MarginCalculation(
    @JsonProperty("totalMargin")
    val totalMargin: Double,

    @JsonProperty("spanMargin")
    val spanMargin: Double,

    @JsonProperty("exposureMargin")
    val exposureMargin: Double,

    @JsonProperty("availableBalance")
    val availableBalance: Double,

    @JsonProperty("variableMargin")
    val variableMargin: Double,

    @JsonProperty("insufficientBalance")
    val insufficientBalance: Double,

    @JsonProperty("brokerage")
    val brokerage: Double,

    @JsonProperty("leverage")
    val leverage: String? = null
)
