package io.github.sonicalgo.dhan.model.response

import com.fasterxml.jackson.annotation.JsonProperty
import io.github.sonicalgo.dhan.model.enums.*

/**
 * Response from place/modify/cancel order operations.
 *
 * @property orderId Order specific identification generated by Dhan
 * @property orderStatus Status of the order: TRANSIT, PENDING, REJECTED, CANCELLED, TRADED, EXPIRED
 *
 * @see <a href="https://dhanhq.co/docs/v2/orders/">DhanHQ Orders API</a>
 */
data class OrderAction(
    @JsonProperty("orderId")
    val orderId: String,

    @JsonProperty("orderStatus")
    val orderStatus: OrderStatus
)

/**
 * Order details from order book.
 *
 * Response from GET /orders, GET /orders/{order-id}, and GET /orders/external/{correlation-id}.
 *
 * @property dhanClientId User specific identification generated by Dhan
 * @property orderId Order specific identification generated by Dhan
 * @property correlationId The user/partner generated id for tracking back
 * @property orderStatus Status of the order
 * @property transactionType BUY or SELL
 * @property exchangeSegment Exchange Segment of instrument
 * @property productType CNC, INTRADAY, MARGIN, MTF, CO, BO
 * @property orderType LIMIT, MARKET, STOP_LOSS, STOP_LOSS_MARKET
 * @property validity DAY or IOC
 * @property tradingSymbol Trading symbol reference
 * @property securityId Exchange standard ID for each scrip
 * @property quantity Number of shares for the order
 * @property disclosedQuantity Number of shares visible
 * @property price Price at which order is placed
 * @property triggerPrice Price at which order is triggered
 * @property afterMarketOrder The order placed is AMO?
 * @property boProfitValue Bracket Order Target Price change
 * @property boStopLossValue Bracket Order Stop Loss Price change
 * @property legName Leg name: ENTRY_LEG, TARGET_LEG, STOP_LOSS_LEG
 * @property createTime Time at which the order is created
 * @property updateTime Time at which the last activity happened
 * @property exchangeTime Time at which order reached at exchange
 * @property drvExpiryDate For F&O, expiry date of contract
 * @property drvOptionType CALL or PUT
 * @property drvStrikePrice For Options, Strike Price
 * @property omsErrorCode Error code in case order rejected/failed
 * @property omsErrorDescription Description of error in case order rejected
 * @property algoId Exchange Algo ID for Dhan
 * @property remainingQuantity Quantity pending (quantity - filledQty)
 * @property averageTradedPrice Average price at which order is traded
 * @property filledQty Quantity of order traded on Exchange
 *
 * @see <a href="https://dhanhq.co/docs/v2/orders/">DhanHQ Orders API</a>
 */
data class OrderBookItem(
    @JsonProperty("dhanClientId")
    val dhanClientId: String,

    @JsonProperty("orderId")
    val orderId: String,

    @JsonProperty("correlationId")
    val correlationId: String? = null,

    @JsonProperty("orderStatus")
    val orderStatus: OrderStatus,

    @JsonProperty("transactionType")
    val transactionType: TransactionType,

    @JsonProperty("exchangeSegment")
    val exchangeSegment: ExchangeSegment,

    @JsonProperty("productType")
    val productType: ProductType,

    @JsonProperty("orderType")
    val orderType: OrderType,

    @JsonProperty("validity")
    val validity: Validity,

    @JsonProperty("tradingSymbol")
    val tradingSymbol: String,

    @JsonProperty("securityId")
    val securityId: String,

    @JsonProperty("quantity")
    val quantity: Int,

    @JsonProperty("disclosedQuantity")
    val disclosedQuantity: Int? = null,

    @JsonProperty("price")
    val price: Double,

    @JsonProperty("triggerPrice")
    val triggerPrice: Double? = null,

    @JsonProperty("afterMarketOrder")
    val afterMarketOrder: Boolean? = null,

    @JsonProperty("boProfitValue")
    val boProfitValue: Double? = null,

    @JsonProperty("boStopLossValue")
    val boStopLossValue: Double? = null,

    @JsonProperty("legName")
    val legName: LegName? = null,

    @JsonProperty("createTime")
    val createTime: String? = null,

    @JsonProperty("updateTime")
    val updateTime: String? = null,

    @JsonProperty("exchangeTime")
    val exchangeTime: String? = null,

    @JsonProperty("drvExpiryDate")
    val drvExpiryDate: String? = null,

    @JsonProperty("drvOptionType")
    val drvOptionType: DrvOptionType? = null,

    @JsonProperty("drvStrikePrice")
    val drvStrikePrice: Double? = null,

    @JsonProperty("omsErrorCode")
    val omsErrorCode: String? = null,

    @JsonProperty("omsErrorDescription")
    val omsErrorDescription: String? = null,

    @JsonProperty("algoId")
    val algoId: String? = null,

    @JsonProperty("remainingQuantity")
    val remainingQuantity: Int? = null,

    @JsonProperty("averageTradedPrice")
    val averageTradedPrice: Double? = null,

    @JsonProperty("filledQty")
    val filledQty: Int? = null
)

/**
 * Trade details from trade book.
 *
 * Response from GET /trades and GET /trades/{order-id}.
 *
 * @property dhanClientId User specific identification generated by Dhan
 * @property orderId Order specific identification generated by Dhan
 * @property exchangeOrderId Order identification generated by exchange
 * @property exchangeTradeId Trade identification generated by exchange
 * @property transactionType BUY or SELL
 * @property exchangeSegment Exchange Segment of instrument
 * @property productType CNC, INTRADAY, MARGIN, MTF, CO, BO
 * @property orderType LIMIT, MARKET, STOP_LOSS, STOP_LOSS_MARKET
 * @property tradingSymbol Trading symbol reference
 * @property securityId Exchange standard ID for each scrip
 * @property tradedQuantity Number of shares executed
 * @property tradedPrice Price at which trade is executed
 * @property createTime Time at which the order is created
 * @property updateTime Time at which the last activity happened
 * @property exchangeTime Time at which order reached at exchange
 * @property drvExpiryDate For F&O, expiry date of contract
 * @property drvOptionType CALL or PUT
 * @property drvStrikePrice For Options, Strike Price
 *
 * @see <a href="https://dhanhq.co/docs/v2/orders/">DhanHQ Orders API</a>
 */
data class TradeBookItem(
    @JsonProperty("dhanClientId")
    val dhanClientId: String,

    @JsonProperty("orderId")
    val orderId: String,

    @JsonProperty("exchangeOrderId")
    val exchangeOrderId: String? = null,

    @JsonProperty("exchangeTradeId")
    val exchangeTradeId: String? = null,

    @JsonProperty("transactionType")
    val transactionType: TransactionType,

    @JsonProperty("exchangeSegment")
    val exchangeSegment: ExchangeSegment,

    @JsonProperty("productType")
    val productType: ProductType,

    @JsonProperty("orderType")
    val orderType: OrderType? = null,

    @JsonProperty("tradingSymbol")
    val tradingSymbol: String? = null,

    @JsonProperty("securityId")
    val securityId: String,

    @JsonProperty("tradedQuantity")
    val tradedQuantity: Int,

    @JsonProperty("tradedPrice")
    val tradedPrice: Double,

    @JsonProperty("createTime")
    val createTime: String? = null,

    @JsonProperty("updateTime")
    val updateTime: String? = null,

    @JsonProperty("exchangeTime")
    val exchangeTime: String? = null,

    @JsonProperty("drvExpiryDate")
    val drvExpiryDate: String? = null,

    @JsonProperty("drvOptionType")
    val drvOptionType: DrvOptionType? = null,

    @JsonProperty("drvStrikePrice")
    val drvStrikePrice: Double? = null
)
