package io.github.sonicalgo.dhan.model.response

import com.fasterxml.jackson.annotation.JsonProperty
import io.github.sonicalgo.dhan.model.enums.DrvOptionType
import io.github.sonicalgo.dhan.model.enums.ExchangeSegment
import io.github.sonicalgo.dhan.model.enums.PositionType
import io.github.sonicalgo.dhan.model.enums.ProductType

/**
 * Holdings data from demat account.
 *
 * Response from GET /holdings endpoint.
 *
 * @property exchange Exchange
 * @property tradingSymbol Trading symbol reference
 * @property securityId Exchange standard ID for each scrip
 * @property isin Universal standard ID for each scrip
 * @property totalQuantity Total quantity
 * @property dematQuantity Quantity delivered in demat account
 * @property t1Quantity Quantity pending delivered in demat account
 * @property availableQuantity Quantity available for transaction
 * @property collateralQuantity Quantity placed as collateral with broker
 * @property averageCostPrice Average Buy Price of total quantity
 *
 * @see <a href="https://dhanhq.co/docs/v2/portfolio/">DhanHQ Portfolio API</a>
 */
data class Holding(
    @JsonProperty("exchange")
    val exchange: String? = null,

    @JsonProperty("tradingSymbol")
    val tradingSymbol: String,

    @JsonProperty("securityId")
    val securityId: String,

    @JsonProperty("isin")
    val isin: String,

    @JsonProperty("totalQty")
    val totalQuantity: Int,

    @JsonProperty("dpQty")
    val dematQuantity: Int,

    @JsonProperty("t1Qty")
    val t1Quantity: Int,

    @JsonProperty("availableQty")
    val availableQuantity: Int,

    @JsonProperty("collateralQty")
    val collateralQuantity: Int,

    @JsonProperty("avgCostPrice")
    val averageCostPrice: Double
)

/**
 * Position data from trading account.
 *
 * Response from GET /positions endpoint.
 *
 * @property dhanClientId User specific identification generated by Dhan
 * @property tradingSymbol Trading symbol reference
 * @property securityId Exchange standard ID for each scrip
 * @property positionType Position Type: LONG, SHORT, CLOSED
 * @property exchangeSegment Exchange and segment (NSE_EQ, NSE_FNO, etc.)
 * @property productType Product type: CNC, INTRADAY, MARGIN, MTF, CO, BO
 * @property buyAverage Average buy price mark to market
 * @property buyQuantity Total quantity bought
 * @property costPrice Actual Cost Price
 * @property sellAverage Average sell price mark to market
 * @property sellQuantity Total quantities sold
 * @property netQuantity buyQty - sellQty = netQty
 * @property realizedProfit Profit or loss booked
 * @property unrealizedProfit Profit or loss standing for open position
 * @property rbiReferenceRate RBI mandated reference rate for forex
 * @property multiplier Multiplying factor for currency F&O
 * @property carryForwardBuyQuantity Carry forward F&O long quantities
 * @property carryForwardSellQuantity Carry forward F&O short quantities
 * @property carryForwardBuyValue Carry forward F&O long value
 * @property carryForwardSellValue Carry forward F&O short value
 * @property dayBuyQuantity Quantities bought today
 * @property daySellQuantity Quantities sold today
 * @property dayBuyValue Value of quantities bought today
 * @property daySellValue Value of quantities sold today
 * @property drvExpiryDate For F&O, expiry date of contract
 * @property drvOptionType Type of Option: CALL, PUT
 * @property drvStrikePrice For Options, Strike Price
 * @property crossCurrency Check for non INR currency pair
 *
 * @see <a href="https://dhanhq.co/docs/v2/portfolio/">DhanHQ Portfolio API</a>
 */
data class Position(
    @JsonProperty("dhanClientId")
    val dhanClientId: String,

    @JsonProperty("tradingSymbol")
    val tradingSymbol: String,

    @JsonProperty("securityId")
    val securityId: String,

    @JsonProperty("positionType")
    val positionType: PositionType,

    @JsonProperty("exchangeSegment")
    val exchangeSegment: ExchangeSegment,

    @JsonProperty("productType")
    val productType: ProductType,

    @JsonProperty("buyAvg")
    val buyAverage: Double,

    @JsonProperty("buyQty")
    val buyQuantity: Int,

    @JsonProperty("costPrice")
    val costPrice: Double,

    @JsonProperty("sellAvg")
    val sellAverage: Double,

    @JsonProperty("sellQty")
    val sellQuantity: Int,

    @JsonProperty("netQty")
    val netQuantity: Int,

    @JsonProperty("realizedProfit")
    val realizedProfit: Double,

    @JsonProperty("unrealizedProfit")
    val unrealizedProfit: Double,

    @JsonProperty("rbiReferenceRate")
    val rbiReferenceRate: Double? = null,

    @JsonProperty("multiplier")
    val multiplier: Int? = null,

    @JsonProperty("carryForwardBuyQty")
    val carryForwardBuyQuantity: Int? = null,

    @JsonProperty("carryForwardSellQty")
    val carryForwardSellQuantity: Int? = null,

    @JsonProperty("carryForwardBuyValue")
    val carryForwardBuyValue: Double? = null,

    @JsonProperty("carryForwardSellValue")
    val carryForwardSellValue: Double? = null,

    @JsonProperty("dayBuyQty")
    val dayBuyQuantity: Int? = null,

    @JsonProperty("daySellQty")
    val daySellQuantity: Int? = null,

    @JsonProperty("dayBuyValue")
    val dayBuyValue: Double? = null,

    @JsonProperty("daySellValue")
    val daySellValue: Double? = null,

    @JsonProperty("drvExpiryDate")
    val drvExpiryDate: String? = null,

    @JsonProperty("drvOptionType")
    val drvOptionType: DrvOptionType? = null,

    @JsonProperty("drvStrikePrice")
    val drvStrikePrice: Double? = null,

    @JsonProperty("crossCurrency")
    val crossCurrency: Boolean? = null
)
