package io.github.sonicalgo.dhan.model.response

import com.fasterxml.jackson.annotation.JsonProperty
import io.github.sonicalgo.dhan.model.enums.*

/**
 * Ledger entry from trading account.
 *
 * @property dhanClientId User specific identification generated by Dhan
 * @property narration Transaction description
 * @property voucherDate Transaction date
 * @property exchange Exchange information
 * @property voucherDescription Nature of transaction
 * @property voucherNumber System-generated transaction number
 * @property debit Debit amount (zero when credit applies)
 * @property credit Credit amount (zero when debit applies)
 * @property runningBalance Account balance after transaction
 *
 * @see <a href="https://dhanhq.co/docs/v2/statements/">DhanHQ Statement API</a>
 */
data class LedgerEntry(
    @JsonProperty("dhanClientId")
    val dhanClientId: String,

    @JsonProperty("narration")
    val narration: String,

    @JsonProperty("voucherdate")
    val voucherDate: String,

    @JsonProperty("exchange")
    val exchange: String? = null,

    @JsonProperty("voucherdesc")
    val voucherDescription: String,

    @JsonProperty("vouchernumber")
    val voucherNumber: String,

    @JsonProperty("debit")
    val debit: String,

    @JsonProperty("credit")
    val credit: String,

    @JsonProperty("runbal")
    val runningBalance: String
)

/**
 * Historical trade record.
 *
 * @property dhanClientId User specific identification generated by Dhan
 * @property orderId Order specific identification generated by Dhan
 * @property exchangeOrderId Order identification generated by exchange
 * @property exchangeTradeId Trade identification generated by exchange
 * @property transactionType BUY or SELL
 * @property exchangeSegment Exchange and segment of instrument
 * @property productType CNC, INTRADAY, MARGIN, MTF, CO, BO
 * @property orderType LIMIT, MARKET, STOP_LOSS, STOP_LOSS_MARKET
 * @property tradingSymbol Order placement symbol
 * @property customSymbol Dhan trading symbol
 * @property securityId Exchange standard ID for each scrip
 * @property tradedQuantity Number of shares executed
 * @property tradedPrice Price at which trade is executed
 * @property isin Universal scrip identifier
 * @property instrument EQUITY or DERIVATIVES
 * @property sebiTax SEBI turnover charges
 * @property stt Securities transaction tax
 * @property brokerageCharges Dhan brokerage fees
 * @property serviceTax Applicable service tax
 * @property exchangeTransactionCharges Exchange transaction fee
 * @property stampDuty Stamp duty charges
 * @property createTime Time at which the order is created
 * @property updateTime Time at which the last activity happened
 * @property exchangeTime Time at which order reached at exchange
 * @property drvExpiryDate For F&O, expiry date of contract
 * @property drvOptionType CALL or PUT
 * @property drvStrikePrice For Options, Strike Price
 *
 * @see <a href="https://dhanhq.co/docs/v2/statements/">DhanHQ Statement API</a>
 */
data class TradeHistory(
    @JsonProperty("dhanClientId")
    val dhanClientId: String,

    @JsonProperty("orderId")
    val orderId: String,

    @JsonProperty("exchangeOrderId")
    val exchangeOrderId: String? = null,

    @JsonProperty("exchangeTradeId")
    val exchangeTradeId: String? = null,

    @JsonProperty("transactionType")
    val transactionType: TransactionType,

    @JsonProperty("exchangeSegment")
    val exchangeSegment: ExchangeSegment,

    @JsonProperty("productType")
    val productType: ProductType,

    @JsonProperty("orderType")
    val orderType: OrderType? = null,

    @JsonProperty("tradingSymbol")
    val tradingSymbol: String? = null,

    @JsonProperty("customSymbol")
    val customSymbol: String? = null,

    @JsonProperty("securityId")
    val securityId: String,

    @JsonProperty("tradedQuantity")
    val tradedQuantity: Int,

    @JsonProperty("tradedPrice")
    val tradedPrice: Double,

    @JsonProperty("isin")
    val isin: String? = null,

    @JsonProperty("instrument")
    val instrument: String? = null,

    @JsonProperty("sebiTax")
    val sebiTax: Double? = null,

    @JsonProperty("stt")
    val stt: Double? = null,

    @JsonProperty("brokerageCharges")
    val brokerageCharges: Double? = null,

    @JsonProperty("serviceTax")
    val serviceTax: Double? = null,

    @JsonProperty("exchangeTransactionCharges")
    val exchangeTransactionCharges: Double? = null,

    @JsonProperty("stampDuty")
    val stampDuty: Double? = null,

    @JsonProperty("createTime")
    val createTime: String? = null,

    @JsonProperty("updateTime")
    val updateTime: String? = null,

    @JsonProperty("exchangeTime")
    val exchangeTime: String? = null,

    @JsonProperty("drvExpiryDate")
    val drvExpiryDate: String? = null,

    @JsonProperty("drvOptionType")
    val drvOptionType: DrvOptionType? = null,

    @JsonProperty("drvStrikePrice")
    val drvStrikePrice: Double? = null
)
