package io.github.sonicalgo.dhan.model.response

import com.fasterxml.jackson.annotation.JsonProperty
import io.github.sonicalgo.dhan.model.enums.*

/**
 * Leg details in a super order.
 *
 * @property orderId Order specific identification generated by Dhan
 * @property legName Leg identification: ENTRY_LEG, TARGET_LEG, STOP_LOSS_LEG
 * @property transactionType BUY or SELL
 * @property totalQuantity Total leg quantity
 * @property remainingQuantity Pending execution quantity
 * @property triggeredQuantity Quantity of Stop Loss or Target legs which has been placed
 * @property price Leg execution price
 * @property orderStatus Leg status
 * @property trailingJump Trail increment for leg
 *
 * @see <a href="https://dhanhq.co/docs/v2/super-order/">DhanHQ Super Order API</a>
 */
data class SuperOrderLegDetail(
    @JsonProperty("orderId")
    val orderId: String? = null,

    @JsonProperty("legName")
    val legName: LegName? = null,

    @JsonProperty("transactionType")
    val transactionType: TransactionType? = null,

    @JsonProperty("totalQuantity")
    val totalQuantity: Int? = null,

    @JsonProperty("remainingQuantity")
    val remainingQuantity: Int? = null,

    @JsonProperty("triggeredQuantity")
    val triggeredQuantity: Int? = null,

    @JsonProperty("price")
    val price: Double? = null,

    @JsonProperty("orderStatus")
    val orderStatus: OrderStatus? = null,

    @JsonProperty("trailingJump")
    val trailingJump: Double? = null
)

/**
 * Super order details from order book.
 *
 * Response from GET /super/orders endpoint.
 *
 * @property dhanClientId User specific identification generated by Dhan
 * @property orderId Order specific identification generated by Dhan
 * @property correlationId The user/partner generated id for tracking back
 * @property orderStatus Status: TRANSIT, PENDING, CLOSED, REJECTED, CANCELLED, PART_TRADED, TRADED
 * @property transactionType BUY or SELL
 * @property exchangeSegment Exchange segment of instrument
 * @property productType CNC, INTRADAY, MARGIN, MTF
 * @property orderType LIMIT or MARKET
 * @property validity Validity of Order: DAY
 * @property tradingSymbol Trading symbol reference
 * @property securityId Exchange standard ID for each scrip
 * @property quantity Number of shares for the order
 * @property remainingQuantity Quantity pending execution
 * @property ltp Last Traded Price of the instrument
 * @property price Price at which order is placed
 * @property afterMarketOrder If the order is placed after market
 * @property legName Leg identification: ENTRY_LEG, TARGET_LEG, STOP_LOSS_LEG
 * @property trailingJump Stop loss trail increment
 * @property exchangeOrderId Exchange generated ID for the order
 * @property createTime Time at which the order is created
 * @property updateTime Last updated time of the order
 * @property exchangeTime Time at which order was sent to the exchange
 * @property omsErrorDescription Description of error in case the order is rejected
 * @property averageTradedPrice Average price at which order is traded
 * @property filledQty Quantity of order traded on Exchange
 * @property triggeredQuantity Quantity of Stop Loss or Target legs placed
 * @property legDetails Nested leg objects
 *
 * @see <a href="https://dhanhq.co/docs/v2/super-order/">DhanHQ Super Order API</a>
 */
data class SuperOrderBookItem(
    @JsonProperty("dhanClientId")
    val dhanClientId: String,

    @JsonProperty("orderId")
    val orderId: String,

    @JsonProperty("correlationId")
    val correlationId: String? = null,

    @JsonProperty("orderStatus")
    val orderStatus: OrderStatus,

    @JsonProperty("transactionType")
    val transactionType: TransactionType,

    @JsonProperty("exchangeSegment")
    val exchangeSegment: ExchangeSegment,

    @JsonProperty("productType")
    val productType: ProductType,

    @JsonProperty("orderType")
    val orderType: OrderType,

    @JsonProperty("validity")
    val validity: Validity? = null,

    @JsonProperty("tradingSymbol")
    val tradingSymbol: String? = null,

    @JsonProperty("securityId")
    val securityId: String,

    @JsonProperty("quantity")
    val quantity: Int,

    @JsonProperty("remainingQuantity")
    val remainingQuantity: Int? = null,

    @JsonProperty("ltp")
    val ltp: Double? = null,

    @JsonProperty("price")
    val price: Double,

    @JsonProperty("afterMarketOrder")
    val afterMarketOrder: Boolean? = null,

    @JsonProperty("legName")
    val legName: LegName? = null,

    @JsonProperty("trailingJump")
    val trailingJump: Double? = null,

    @JsonProperty("exchangeOrderId")
    val exchangeOrderId: String? = null,

    @JsonProperty("createTime")
    val createTime: String? = null,

    @JsonProperty("updateTime")
    val updateTime: String? = null,

    @JsonProperty("exchangeTime")
    val exchangeTime: String? = null,

    @JsonProperty("omsErrorDescription")
    val omsErrorDescription: String? = null,

    @JsonProperty("averageTradedPrice")
    val averageTradedPrice: Double? = null,

    @JsonProperty("filledQty")
    val filledQty: Int? = null,

    @JsonProperty("triggeredQuantity")
    val triggeredQuantity: Int? = null,

    @JsonProperty("legDetails")
    val legDetails: List<SuperOrderLegDetail>? = null
)
