package io.github.sonicalgo.dhan.model.response

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Response from kill switch operation.
 *
 * @property dhanClientId User specific identification number generated by Dhan
 * @property killSwitchStatus Confirmation message indicating activation/deactivation status
 *
 * @see <a href="https://dhanhq.co/docs/v2/traders-control/">DhanHQ Trader's Control API</a>
 */
data class KillSwitchResult(
    @JsonProperty("dhanClientId")
    val dhanClientId: String,

    @JsonProperty("killSwitchStatus")
    val killSwitchStatus: String
)
