package io.github.sonicalgo.dhan.model.request

import com.fasterxml.jackson.annotation.JsonProperty
import io.github.sonicalgo.dhan.Dhan
import io.github.sonicalgo.dhan.model.enums.*

/**
 * Request parameters for placing a super order.
 *
 * Super orders include entry, target, and stop loss legs with trailing stop loss functionality.
 *
 * @property dhanClientId Optional. Auto-injected from [Dhan] config if not provided.
 * @property correlationId The user/partner generated id for tracking back
 * @property transactionType The trading side of transaction: BUY, SELL
 * @property exchangeSegment Exchange segment of instrument
 * @property productType Product type: CNC, INTRADAY, MARGIN, MTF
 * @property orderType Order Type: LIMIT, MARKET
 * @property securityId Exchange standard ID for each scrip
 * @property quantity Number of shares for the order
 * @property price Price at which order is placed
 * @property targetPrice Target Price for the Super Order
 * @property stopLossPrice Stop Loss Price for the Super Order
 * @property trailingJump Price Jump by which Stop Loss should be trailed
 *
 * @see <a href="https://dhanhq.co/docs/v2/super-order/">DhanHQ Super Order API</a>
 */
data class PlaceSuperOrderParams(
    @JsonProperty("dhanClientId")
    val dhanClientId: String? = null,

    @JsonProperty("correlationId")
    val correlationId: String? = null,

    @JsonProperty("transactionType")
    val transactionType: TransactionType,

    @JsonProperty("exchangeSegment")
    val exchangeSegment: ExchangeSegment,

    @JsonProperty("productType")
    val productType: ProductType,

    @JsonProperty("orderType")
    val orderType: OrderType,

    @JsonProperty("securityId")
    val securityId: String,

    @JsonProperty("quantity")
    val quantity: Int,

    @JsonProperty("price")
    val price: Double,

    @JsonProperty("targetPrice")
    val targetPrice: Double,

    @JsonProperty("stopLossPrice")
    val stopLossPrice: Double,

    @JsonProperty("trailingJump")
    val trailingJump: Double
)

/**
 * Request parameters for modifying a super order.
 *
 * Use legName to specify which leg to modify:
 * - ENTRY_LEG: Modify entry order (orderType, quantity, price, targetPrice, stopLossPrice, trailingJump)
 * - TARGET_LEG: Modify target price only (targetPrice)
 * - STOP_LOSS_LEG: Modify stop loss (stopLossPrice, trailingJump)
 *
 * @property dhanClientId Optional. Auto-injected from [Dhan] config if not provided.
 * @property orderId Order specific identification generated by Dhan
 * @property legName Leg to modify: ENTRY_LEG, TARGET_LEG, or STOP_LOSS_LEG
 * @property orderType Order Type: LIMIT, MARKET (conditionally required for ENTRY_LEG)
 * @property quantity Quantity to be modified (conditionally required for ENTRY_LEG)
 * @property price Price to be modified (conditionally required for ENTRY_LEG)
 * @property targetPrice Target Price to be modified (for ENTRY_LEG or TARGET_LEG)
 * @property stopLossPrice Stop Loss Price to be modified (for ENTRY_LEG or STOP_LOSS_LEG)
 * @property trailingJump Stop Loss Price jump to be modified (for ENTRY_LEG or STOP_LOSS_LEG)
 *
 * @see <a href="https://dhanhq.co/docs/v2/super-order/">DhanHQ Super Order API</a>
 */
data class ModifySuperOrderParams(
    @JsonProperty("dhanClientId")
    val dhanClientId: String? = null,

    @JsonProperty("orderId")
    val orderId: String,

    @JsonProperty("legName")
    val legName: LegName,

    @JsonProperty("orderType")
    val orderType: OrderType? = null,

    @JsonProperty("quantity")
    val quantity: Int? = null,

    @JsonProperty("price")
    val price: Double? = null,

    @JsonProperty("targetPrice")
    val targetPrice: Double? = null,

    @JsonProperty("stopLossPrice")
    val stopLossPrice: Double? = null,

    @JsonProperty("trailingJump")
    val trailingJump: Double? = null
)
